// Auto-generated from Prague_Lawyers_Directory.xlsx
// 100 real Prague law firms – profiles by firm

const lawyersData = [
  {
    "id": 1,
    "name": "Jaroslav Havel",
    "firm": "HAVEL & PARTNERS",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 24,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Soutěžní právo",
      "Spory a rozhodčí řízení",
      "IT právo"
    ],
    "type": "Velká národní kancelář",
    "founded": 2001,
    "size": "350+",
    "verified": true,
    "key_partner": "Jaroslav Havel",
    "description": "Největší nezávislá advokátní kancelář v České republice a na Slovensku se 6 pobočkami v regionu CEE",
    "website": "www.havelpartners.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština",
      "Slovenština",
      "Ruština",
      "Polština",
      "Italština",
      "Španělština"
    ],
    "initials": "HA",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Largest independent Czech/Slovak firm",
    "ranking": "Tier 1 – Legal 500; Band 1 – Chambers",
    "awards": "Law Firm of the Year (multiple years)",
    "target": "Korporace, banky, státní správa",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 2,
    "name": "Ota Mach",
    "firm": "Kocián Šolc Balaštík",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 31,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Bankovní právo",
      "Soutěžní právo",
      "Spory a rozhodčí řízení",
      "Pracovní právo"
    ],
    "type": "Velká národní kancelář",
    "founded": 1990,
    "size": "60+",
    "verified": false,
    "key_partner": "Ota Mach",
    "description": "Jedna z nejstarších nezávislých českých advokátních kanceláří, známá vysokou kvalitou poradenství",
    "website": "www.ksb.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "KŠ",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Premium Czech independent firm",
    "ranking": "Tier 1 – Legal 500",
    "awards": "Recommended – Chambers Europe",
    "target": "Korporace, banky, fondy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 3,
    "name": "Kateřina Winterling Vorlíčková",
    "firm": "BBH advokátní kancelář",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 38,
    "areas": [
      "Bankovní právo",
      "Fúze a akvizice",
      "Finanční regulace",
      "Soutěžní právo",
      "Insolvence",
      "Nemovitosti"
    ],
    "type": "Velká národní kancelář",
    "founded": 1995,
    "size": "110+",
    "verified": false,
    "key_partner": "Kateřina Winterling Vorlíčková",
    "description": "Přední kancelář s hlubokou expertízou v oblasti bankovnictví, financí a regulace",
    "website": "www.bbh.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Slovenština"
    ],
    "initials": "BB",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Prague & Bratislava offices",
    "ranking": "Tier 1 – Legal 500 (Banking)",
    "awards": "Market leader Banking & Finance",
    "target": "Banky, finanční instituce, korporace",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 4,
    "name": "Jan Juroška",
    "firm": "Kinstellar",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 45,
    "areas": [
      "Bankovní právo",
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Fúze a akvizice",
      "Technologie, média a telekomunikace",
      "Life Sciences"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2008,
    "size": "40+",
    "verified": true,
    "key_partner": "Jan Juroška",
    "description": "Přední advokátní kancelář regionu CEE s pobočkami v 10 zemích",
    "website": "www.kinstellar.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Slovenština"
    ],
    "initials": "KI",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "CEE network across 10 offices",
    "ranking": "Tier 1 – Legal 500 (multiple)",
    "awards": "Chambers Ranked",
    "target": "Korporace, PE fondy, nadnárodní firmy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 5,
    "name": "Miloš Olík",
    "firm": "ROWAN LEGAL",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 7,
    "areas": [
      "Spory a rozhodčí řízení",
      "Soutěžní právo",
      "IT právo",
      "Správní právo",
      "Fúze a akvizice",
      "Nemovitosti"
    ],
    "type": "Střední národní kancelář",
    "founded": 2013,
    "size": "90+",
    "verified": true,
    "key_partner": "Miloš Olík",
    "description": "Oceňovaná kancelář specializující se na IT právo, duševní vlastnictví a environmentální právo",
    "website": "www.rowan.legal",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "RO",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong in IT law and public procurement",
    "ranking": "Tier 1 – Legal 500 (IT Law)",
    "awards": "Law Firm of the Year 2025 – IP, IT, Environmental",
    "target": "Technologické firmy, stát, korporace",
    "primary": "IT právo a technologie"
  },
  {
    "id": 6,
    "name": "Weinhold Legal",
    "firm": "Weinhold Legal",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 14,
    "areas": [
      "Fúze a akvizice",
      "Financování",
      "Pojišťovací právo",
      "Obchodní právo",
      "Pracovní právo",
      "Spory a rozhodčí řízení"
    ],
    "type": "Střední národní kancelář",
    "founded": 1996,
    "size": "40+",
    "verified": false,
    "key_partner": "",
    "description": "Zavedená česká kancelář se silnou praxí v oblasti korporátního práva a fúzí",
    "website": "www.weinholdlegal.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "WE",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong Czech market player since 1996",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Korporace, pojišťovny, nadnárodní firmy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 7,
    "name": "Clifford Chance Prague",
    "firm": "Clifford Chance Prague",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 21,
    "areas": [
      "Fúze a akvizice",
      "Bankovní právo",
      "Insolvence",
      "Energetika",
      "Nemovitosti",
      "Soutěžní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "50+",
    "verified": true,
    "key_partner": "",
    "description": "Globální kancelář ze skupiny Magic Circle s vedoucím postavením v Praze",
    "website": "www.cliffordchance.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština"
    ],
    "initials": "CC",
    "hourly_rate": "5,000–8,000+",
    "consult_fee": "By arrangement",
    "pricing_note": "Magic Circle premium rates",
    "ranking": "Tier 1 – Legal 500 (multiple)",
    "awards": "Leading international firm",
    "target": "Nadnárodní firmy, banky, PE fondy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 8,
    "name": "Jan Andrušsko",
    "firm": "White & Case Prague",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 28,
    "areas": [
      "Fúze a akvizice",
      "Private Equity",
      "Bankovní právo",
      "Insolvence",
      "Energetika",
      "Nemovitosti"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "50+",
    "verified": true,
    "key_partner": "Jan Andrušsko",
    "description": "Oceňovaná globální kancelář s hlubokou znalostí regionu CEE",
    "website": "www.whitecase.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Slovenština"
    ],
    "initials": "WC",
    "hourly_rate": "5,000–8,000+",
    "consult_fee": "By arrangement",
    "pricing_note": "Czech Republic Firm of the Year – Legal 500 CEE 2025",
    "ranking": "Tier 1 – Legal 500",
    "awards": "Firm of the Year CEE 2025",
    "target": "Nadnárodní firmy, banky, PE fondy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 9,
    "name": "Miroslav Dubovský",
    "firm": "DLA Piper Prague",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 35,
    "areas": [
      "Fúze a akvizice",
      "Obchodní právo",
      "Bankovní právo",
      "Insolvence",
      "Nemovitosti",
      "Stavební právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2004,
    "size": "25+",
    "verified": true,
    "key_partner": "Miroslav Dubovský",
    "description": "Globální advokátní kancelář s komplexní českou praxí",
    "website": "www.dlapiper.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "DP",
    "hourly_rate": "4,000–7,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Global network, 90+ offices worldwide",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Nadnárodní firmy, korporace, banky",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 10,
    "name": "Tomáš Matějovský",
    "firm": "CMS Prague",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 42,
    "areas": [
      "Soutěžní právo",
      "Bankovní právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Spory a rozhodčí řízení",
      "Pracovní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "40+",
    "verified": true,
    "key_partner": "Tomáš Matějovský",
    "description": "Přední mezinárodní kancelář se silnou přítomností v regionu CEE",
    "website": "www.cms.law",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština"
    ],
    "initials": "CP",
    "hourly_rate": "4,000–6,500",
    "consult_fee": "By arrangement",
    "pricing_note": "84 offices in 47 countries",
    "ranking": "Tier 1 – Legal 500 (Competition)",
    "awards": "Chambers Ranked",
    "target": "Korporace, banky, technologické firmy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 11,
    "name": "Ladislav Smejkal",
    "firm": "Dentons Prague",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 4,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Private Equity",
      "Bankovní právo",
      "Nemovitosti",
      "Pracovní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2013,
    "size": "35+",
    "verified": false,
    "key_partner": "Ladislav Smejkal",
    "description": "Největší advokátní kancelář světa s pobočkou v Praze",
    "website": "www.dentons.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Ruština"
    ],
    "initials": "DP",
    "hourly_rate": "4,000–7,000",
    "consult_fee": "By arrangement",
    "pricing_note": "World's largest law firm by headcount",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Nadnárodní firmy, banky, stát",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 12,
    "name": "Tomáš Skoumal",
    "firm": "Baker McKenzie Prague",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 11,
    "areas": [
      "Fúze a akvizice",
      "Private Equity",
      "Bankovní právo",
      "Spory a rozhodčí řízení",
      "Nemovitosti",
      "Pracovní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "30+",
    "verified": true,
    "key_partner": "Tomáš Skoumal",
    "description": "Jedna z prvních mezinárodních kanceláří, která otevřela pobočku v Praze",
    "website": "www.bakermckenzie.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "BM",
    "hourly_rate": "4,500–7,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Pioneer international firm in Prague",
    "ranking": "Tier 1 – Legal 500 (Tax)",
    "awards": "Chambers Ranked",
    "target": "Nadnárodní firmy, banky, korporace",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 13,
    "name": "A&O Shearman Prague",
    "firm": "A&O Shearman Prague",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 18,
    "areas": [
      "Bankovní právo",
      "Spory a rozhodčí řízení",
      "Nemovitosti",
      "Obchodní právo",
      "Soutěžní právo",
      "Životní prostředí"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "40+",
    "verified": true,
    "key_partner": "",
    "description": "Kancelář ze skupiny Magic Circle se silnou bankovní a finanční praxí v Praze",
    "website": "www.aoshearman.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Francouzština",
      "Němčina"
    ],
    "initials": "OS",
    "hourly_rate": "5,000–8,000+",
    "consult_fee": "By arrangement",
    "pricing_note": "Magic Circle firm (formerly Allen & Overy)",
    "ranking": "Tier 1 – Legal 500 (Banking)",
    "awards": "Leading international firm",
    "target": "Banky, nadnárodní společnosti, PE fondy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 14,
    "name": "Rostislav Pekař",
    "firm": "Squire Patton Boggs Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 25,
    "areas": [
      "Spory a rozhodčí řízení",
      "Obchodní právo",
      "Fúze a akvizice",
      "Nemovitosti",
      "Pracovní právo",
      "Bankovní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "20+",
    "verified": false,
    "key_partner": "Rostislav Pekař",
    "description": "Dlouhodobě zavedená mezinárodní kancelář se silnou sporovou praxí",
    "website": "www.squirepattonboggs.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "SP",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "One of the longest-established in Prague",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Korporace, státní správa, investoři",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 15,
    "name": "Vladimír Čížek",
    "firm": "Schoenherr Prague",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 32,
    "areas": [
      "Fúze a akvizice",
      "Insolvence",
      "Bankovní právo",
      "Soutěžní právo",
      "Nemovitosti",
      "Compliance"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1993,
    "size": "25+",
    "verified": false,
    "key_partner": "Vladimír Čížek",
    "description": "Kancelář se sídlem v Rakousku a silnou přítomností v regionu CEE",
    "website": "www.schoenherr.eu",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "SP",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong CEE/SEE network",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Korporace, banky, investoři",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 16,
    "name": "PRK Partners",
    "firm": "PRK Partners",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 39,
    "areas": [
      "Bankovní právo",
      "Fúze a akvizice",
      "Obchodní právo",
      "Nemovitosti",
      "Pracovní právo",
      "Spory a rozhodčí řízení"
    ],
    "type": "Velká národní kancelář",
    "founded": 1993,
    "size": "100+",
    "verified": true,
    "key_partner": "",
    "description": "Přední nezávislá česká kancelář s komplexní právní praxí",
    "website": "www.prkpartners.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Francouzština",
      "Němčina",
      "Slovenština",
      "Ruština"
    ],
    "initials": "PR",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "One of the largest Czech independent firms",
    "ranking": "Tier 1 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Korporace, banky, státní správa",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 17,
    "name": "Petr Kuhn",
    "firm": "BADOKH",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 46,
    "areas": [
      "Fúze a akvizice",
      "Insolvence",
      "Financování",
      "Obchodní právo",
      "Nemovitosti",
      "Spory a rozhodčí řízení"
    ],
    "type": "Butique kancelář",
    "founded": 2014,
    "size": "35",
    "verified": false,
    "key_partner": "Petr Kuhn",
    "description": "Boutique kancelář známá prací v oblasti restrukturalizace a insolvence",
    "website": "www.badokh.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "BA",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Senior advocates and tax advisors",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Highly respected restructuring practice",
    "target": "Korporace, banky, distressed aktiva",
    "primary": "Fúze a restrukturalizace"
  },
  {
    "id": 18,
    "name": "Radka Konečná",
    "firm": "Konečná & Zacha",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 8,
    "areas": [
      "Nemovitosti",
      "Fúze a akvizice",
      "Bankovní právo",
      "Financování",
      "Obchodní právo",
      "Pracovní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 1987,
    "size": "20+",
    "verified": false,
    "key_partner": "Radka Konečná",
    "description": "Zavedená česká kancelář se silnou praxí v oblasti nemovitostí a korporátního práva",
    "website": "www.konecna-zacha.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "KZ",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "One of the oldest Czech firms",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Korporace, developeři, banky",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 19,
    "name": "Vladimíra Glatzová",
    "firm": "Glatzova & Co",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 15,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Spory a rozhodčí řízení",
      "Nemovitosti",
      "Bankovní právo",
      "Pracovní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 1994,
    "size": "50",
    "verified": false,
    "key_partner": "Vladimíra Glatzová",
    "description": "Dobře zavedená česká kancelář se širokým záběrem právní praxe",
    "website": "www.glatzova.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "GC",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Respected mid-size Czech firm",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Best Law Firm ranking",
    "target": "Korporace, SME, nadnárodní firmy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 20,
    "name": "Radovan Kubáč",
    "firm": "Nedelka Kubáč advokáti",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 22,
    "areas": [
      "Soutěžní právo",
      "Regulatorní právo",
      "Správní právo",
      "Compliance"
    ],
    "type": "Butique kancelář",
    "founded": 2013,
    "size": "15+",
    "verified": false,
    "key_partner": "Radovan Kubáč",
    "description": "Přední boutique kancelář specializující se na soutěžní a regulatorní právo",
    "website": "www.nka.eu",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "NK",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Top-tier competition law specialists",
    "ranking": "Band 1 – Chambers (Competition)",
    "awards": "Leading competition firm",
    "target": "Korporace, regulovaná odvětví",
    "primary": "Soutěžní právo"
  },
  {
    "id": 21,
    "name": "Marcela Vilímková",
    "firm": "Vilímková Dudák & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 29,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Zdravotnictví",
      "Farmaceutické právo",
      "Daně",
      "Nemovitosti"
    ],
    "type": "Střední národní kancelář",
    "founded": 1997,
    "size": "40+",
    "verified": false,
    "key_partner": "Marcela Vilímková",
    "description": "Středně velká kancelář s pozoruhodnou expertízou ve zdravotnictví a farmacii",
    "website": "www.vilimkovadudak.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "VD",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong healthcare/pharma specialization",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Healthcare law specialists",
    "target": "Zdravotnictví, korporace, SME",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 22,
    "name": "Martin Řanda",
    "firm": "ŘANDA HAVEL LEGAL (act legal)",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 36,
    "areas": [
      "Spory a rozhodčí řízení",
      "Obchodní právo",
      "Fúze a akvizice",
      "Stavební právo",
      "Energetika",
      "Financování"
    ],
    "type": "Butique kancelář",
    "founded": 2005,
    "size": "15+",
    "verified": false,
    "key_partner": "Martin Řanda",
    "description": "Boutique kancelář zaměřená na spory, energetiku a stavebnictví",
    "website": "www.randalegal.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "ŘH",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of act legal international network",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Strong dispute resolution",
    "target": "Korporace, energetické firmy, developeři",
    "primary": "Řešení sporů"
  },
  {
    "id": 23,
    "name": "Petr Bříza",
    "firm": "Bříza & Trubač",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 43,
    "areas": [
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Soutěžní právo",
      "Duševní vlastnictví",
      "Právo EU"
    ],
    "type": "Butique kancelář",
    "founded": 2013,
    "size": "8",
    "verified": false,
    "key_partner": "Petr Bříza",
    "description": "Malá boutique kancelář vynikající v mezinárodní arbitráži a právu EU",
    "website": "www.brizatrubac.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "BT",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Highly regarded in arbitration",
    "ranking": "Band 4 – Chambers Global",
    "awards": "Leading arbitration boutique",
    "target": "Korporace, mezinárodní spory",
    "primary": "Spory a rozhodčí řízení"
  },
  {
    "id": 24,
    "name": "ARROWS advokátní kancelář",
    "firm": "ARROWS advokátní kancelář",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 5,
    "areas": [
      "Občanské právo",
      "Obchodní právo",
      "Rodinné právo",
      "Pracovní právo",
      "Smluvní právo",
      "Trestní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 2014,
    "size": "20+",
    "verified": true,
    "key_partner": "",
    "description": "Moderní kancelář pokrývající širokou škálu spotřebitelského a obchodního práva",
    "website": "www.arws.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "AR",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Consumer-friendly, broad practice",
    "ranking": "N/A",
    "awards": "Growing national firm",
    "target": "SME, fyzické osoby, startupy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 25,
    "name": "Pavel Randl",
    "firm": "Randl Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 12,
    "areas": [
      "Pracovní právo",
      "Obchodní právo",
      "Marketingové právo",
      "Mediální právo",
      "Duševní vlastnictví",
      "IT právo"
    ],
    "type": "Butique kancelář",
    "founded": 2009,
    "size": "12+",
    "verified": false,
    "key_partner": "Pavel Randl",
    "description": "Specializovaná boutique kancelář pracovního práva, člen globální sítě",
    "website": "www.randls.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Ruština",
      "Francouzština"
    ],
    "initials": "RA",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Ius Laboris member (global employment network)",
    "ranking": "Tier 1 – Legal 500 (Employment)",
    "awards": "Leading employment law firm",
    "target": "Korporace, HR oddělení",
    "primary": "Pracovní právo"
  },
  {
    "id": 26,
    "name": "Jakub Málek",
    "firm": "PEYTON legal",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 19,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "IT právo",
      "Smluvní právo",
      "Nemovitosti"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "18",
    "verified": false,
    "key_partner": "Jakub Málek",
    "description": "Boutique kancelář s rostoucí reputací v oblasti ochrany dat a korporátního práva",
    "website": "www.peytonlegal.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "PE",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong data protection focus",
    "ranking": "N/A",
    "awards": "GDPR specialists",
    "target": "Technologické firmy, SME, korporace",
    "primary": "Korporátní právo a ochrana dat"
  },
  {
    "id": 27,
    "name": "Roman Felix",
    "firm": "Felix a spol.",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 26,
    "areas": [
      "Obchodní právo",
      "Občanské právo",
      "Fúze a akvizice",
      "Smluvní právo",
      "Spory a rozhodčí řízení",
      "Duševní vlastnictví"
    ],
    "type": "Střední národní kancelář",
    "founded": 1998,
    "size": "23",
    "verified": true,
    "key_partner": "Roman Felix",
    "description": "Zavedená kancelář pokrývající obchodní a občanskoprávní agendu",
    "website": "www.akf.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Polština"
    ],
    "initials": "FE",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Long-established Czech firm",
    "ranking": "Recommended – Legal 500",
    "awards": "Czech Law Firm award",
    "target": "SME, fyzické osoby, korporace",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 28,
    "name": "Eversheds Sutherland Prague",
    "firm": "Eversheds Sutherland Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 33,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Spory a rozhodčí řízení",
      "Nemovitosti",
      "Energetika"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2004,
    "size": "50+",
    "verified": false,
    "key_partner": "",
    "description": "Globální kancelář se silným českým týmem (dříve Dvořák Hager)",
    "website": "www.eversheds-sutherland.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "ES",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Merged with Dvořák Hager & Partners",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Global network – 74 offices",
    "target": "Nadnárodní firmy, korporace, banky",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 29,
    "name": "Robert David",
    "firm": "Wolf Theiss Prague",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 40,
    "areas": [
      "Bankovní právo",
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Pracovní právo",
      "Nemovitosti",
      "Regulatorní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1998,
    "size": "30+",
    "verified": false,
    "key_partner": "Robert David",
    "description": "Mezinárodní kancelář zaměřená na CEE se silnou pražskou pobočkou",
    "website": "www.wolftheiss.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "WT",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Austrian-origin CEE specialist",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Banky, korporace, investoři",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 30,
    "name": "Karin Pomaizlová",
    "firm": "Taylor Wessing Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 47,
    "areas": [
      "Duševní vlastnictví",
      "Obchodní právo",
      "Nemovitosti",
      "Stavební právo",
      "Pracovní právo",
      "Daně"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1998,
    "size": "40",
    "verified": false,
    "key_partner": "Karin Pomaizlová",
    "description": "Mezinárodní kancelář s výraznými silnými stránkami v IP, technologiích a nemovitostech",
    "website": "www.taylorwessing.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "TW",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Known for IP/tech and real estate",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Strong IP/Tech practice",
    "target": "Technologické firmy, vývojáři, korporace",
    "primary": "Duševní vlastnictví a technologie"
  },
  {
    "id": 31,
    "name": "Barbara Kusak",
    "firm": "Noerr Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 9,
    "areas": [
      "Fúze a akvizice",
      "Insolvence",
      "Financování",
      "Leasing",
      "Pracovní právo",
      "Compliance"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2000,
    "size": "20+",
    "verified": false,
    "key_partner": "Barbara Kusak",
    "description": "Kancelář se sídlem v Německu se silnou klientelou v regionu CEE",
    "website": "www.noerr.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "NP",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "German-origin firm with CEE network",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Chambers Ranked",
    "target": "Německé korporace, banky, investoři",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 32,
    "name": "Monika Rutland",
    "firm": "Rutland & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 16,
    "areas": [
      "Obchodní právo",
      "Nemovitosti",
      "Fúze a akvizice",
      "Obhajoba",
      "Medicínské právo",
      "IT právo"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "15+",
    "verified": false,
    "key_partner": "Monika Rutland",
    "description": "Boutique kancelář se silným zaměřením na nemovitosti a sektorové poradenství",
    "website": "www.rutlandandpartners.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "RU",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Boutique with sector focus",
    "ranking": "Recommended – Legal 500",
    "awards": "Growing boutique",
    "target": "SME, developeři, investoři",
    "primary": "Korporátní právo a nemovitosti"
  },
  {
    "id": 33,
    "name": "Richard Gürlich",
    "firm": "Gürlich & Co",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 23,
    "areas": [
      "Fúze a akvizice",
      "Transakce",
      "Nemovitosti",
      "Duševní vlastnictví",
      "Obchodní právo",
      "Občanské právo"
    ],
    "type": "Butique kancelář",
    "founded": 2002,
    "size": "10+",
    "verified": false,
    "key_partner": "Richard Gürlich",
    "description": "Boutique kancelář známá transakcemi a veřejnými zakázkami",
    "website": "www.akrg.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "GC",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong public procurement practice",
    "ranking": "Outstanding ranking 2025",
    "awards": "Public procurement specialist",
    "target": "Státní správa, korporace, SME",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 34,
    "name": "Multiple Lawyers",
    "firm": "Czech Immigration & Visa Solutions",
    "city": "Praha",
    "rating": 4.6,
    "reviews": 30,
    "areas": [
      "Imigrace",
      "Víza",
      "Pracovní povolení",
      "Pobytová práva",
      "Duševní vlastnictví"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "5+",
    "verified": true,
    "key_partner": "Multiple Lawyers",
    "description": "Specializovaná imigrační kancelář pomáhající expatům a firmám s českými vízy",
    "website": "www.czechvisalawyer.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Ruština"
    ],
    "initials": "CI",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "Initial consultation from 2,000 CZK",
    "pricing_note": "Specialized immigration boutique",
    "ranking": "N/A",
    "awards": "Top-rated immigration specialists",
    "target": "Expati, firmy zaměstnávající cizince",
    "primary": "Imigrační právo"
  },
  {
    "id": 35,
    "name": "Peterka & Partners",
    "firm": "Peterka & Partners",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 37,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Nemovitosti",
      "Spory a rozhodčí řízení",
      "Pracovní právo",
      "Imigrace"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1998,
    "size": "80+",
    "verified": true,
    "key_partner": "",
    "description": "Mezinárodní kancelář s pobočkami v celém regionu CEE a silnými vícejazyčnými schopnostmi",
    "website": "www.peterkapartners.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština",
      "Španělština",
      "Ruština"
    ],
    "initials": "PE",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "International network across CEE",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Multi-office CEE firm",
    "target": "Nadnárodní firmy, SME, expati",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 36,
    "name": "Martin Švehlík",
    "firm": "Švehlík & Mikuláš advokáti",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 44,
    "areas": [
      "Rodinné právo",
      "Rozvod",
      "Péče o děti",
      "Dědické právo",
      "Občanské právo"
    ],
    "type": "Butique kancelář",
    "founded": 2008,
    "size": "5",
    "verified": true,
    "key_partner": "Martin Švehlík",
    "description": "Boutique kancelář zaměřená na rodinné právo včetně rozvodu a péče o děti",
    "website": "www.smak.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "ŠM",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation 1,500 CZK",
    "pricing_note": "Family law specialists",
    "ranking": "N/A",
    "awards": "Recommended family law firm",
    "target": "Fyzické osoby, rodiny",
    "primary": "Rodinné právo"
  },
  {
    "id": 37,
    "name": "Robert Dohnal",
    "firm": "DOHNAL PERTOT SLANINA",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 6,
    "areas": [
      "Trestní právo",
      "Spory a rozhodčí řízení",
      "Obchodní právo",
      "Nemovitosti"
    ],
    "type": "Střední národní kancelář",
    "founded": 2005,
    "size": "15+",
    "verified": true,
    "key_partner": "Robert Dohnal",
    "description": "Kancelář se silnou sporovou a trestněprávní obhajobou",
    "website": "www.akdps.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "DP",
    "hourly_rate": "2,000–4,000",
    "consult_fee": "First consultation from 2,000 CZK",
    "pricing_note": "Strong criminal defense practice",
    "ranking": "N/A",
    "awards": "Experienced criminal defense",
    "target": "Fyzické osoby, korporace",
    "primary": "Trestní právo a spory"
  },
  {
    "id": 38,
    "name": "Jiří Mach",
    "firm": "MACH LEGAL",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 13,
    "areas": [
      "Nemovitosti",
      "Stavební právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Spory a rozhodčí řízení"
    ],
    "type": "Butique kancelář",
    "founded": 2012,
    "size": "10+",
    "verified": false,
    "key_partner": "Jiří Mach",
    "description": "Boutique kancelář specializující se na realitní transakce a stavební právo",
    "website": "www.machlegal.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "MA",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Real estate transaction specialists",
    "ranking": "N/A",
    "awards": "Real estate focused",
    "target": "Developeři, investoři, banky",
    "primary": "Nemovitosti a stavební právo"
  },
  {
    "id": 39,
    "name": "Jaroslav Fiala",
    "firm": "Fiala, Tejkal a partneři",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 20,
    "areas": [
      "Daně",
      "Obchodní právo",
      "Fúze a akvizice",
      "Nemovitosti",
      "Spory a rozhodčí řízení",
      "Bankovní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 1994,
    "size": "20+",
    "verified": false,
    "key_partner": "Jaroslav Fiala",
    "description": "Zavedená kancelář s hlubokou expertízou v daňovém právu a korporátním poradenství",
    "website": "www.akfiala.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "FT",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong tax advisory practice",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Tax law specialists",
    "target": "Korporace, movití jednotlivci, banky",
    "primary": "Daňové právo"
  },
  {
    "id": 40,
    "name": "Ondřej Havlíček",
    "firm": "Pierstone",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 27,
    "areas": [
      "Investiční fondy",
      "Regulatorní právo",
      "Obchodní právo",
      "Fintech",
      "Bankovní právo"
    ],
    "type": "Butique kancelář",
    "founded": 2018,
    "size": "10+",
    "verified": false,
    "key_partner": "Ondřej Havlíček",
    "description": "Specializovaná kancelář zaměřená na investiční fondy, fintech a regulaci",
    "website": "www.pierstone.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "PI",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Specialist in funds and fintech regulation",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Funds regulation expert",
    "target": "Správci fondů, fintech, banky",
    "primary": "Fondy a investice"
  },
  {
    "id": 41,
    "name": "Tomáš Čihula",
    "firm": "CIKR advokátní kancelář",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 34,
    "areas": [
      "Insolvence",
      "Spory a rozhodčí řízení",
      "Obchodní právo"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "8",
    "verified": true,
    "key_partner": "Tomáš Čihula",
    "description": "Boutique kancelář specializující se na insolvenci, restrukturalizaci a obchodní spory",
    "website": "www.cikr.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "CI",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Insolvency specialists",
    "ranking": "N/A",
    "awards": "Insolvency practice specialists",
    "target": "Korporace, věřitelé, banky",
    "primary": "Insolvence a restrukturalizace"
  },
  {
    "id": 42,
    "name": "Petr Dostál",
    "firm": "epravo.cz / Dostál Advokáti",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 41,
    "areas": [
      "Občanské právo",
      "Obchodní právo",
      "Smluvní právo",
      "Spory a rozhodčí řízení",
      "Nemovitosti"
    ],
    "type": "Butique kancelář",
    "founded": 2008,
    "size": "5",
    "verified": true,
    "key_partner": "Petr Dostál",
    "description": "Přístupná boutique kancelář nabízející dostupné právní služby",
    "website": "www.dostaladvokati.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "E/",
    "hourly_rate": "1,500–2,500",
    "consult_fee": "First consultation from 1,000 CZK",
    "pricing_note": "Budget-friendly option",
    "ranking": "N/A",
    "awards": "Consumer-friendly",
    "target": "Fyzické osoby, malé firmy",
    "primary": "Občanské a obchodní právo"
  },
  {
    "id": 43,
    "name": "Pavel Němec",
    "firm": "AK Němec, Bláha & Navrátilová",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 48,
    "areas": [
      "Pracovní právo",
      "Diskriminace",
      "Sociální zabezpečení",
      "Insolvence"
    ],
    "type": "Střední národní kancelář",
    "founded": 2005,
    "size": "15+",
    "verified": false,
    "key_partner": "Pavel Němec",
    "description": "Kancelář se silným zaměřením na pracovní právo a zaměstnaneckou agendu",
    "website": "www.aknbn.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "AN",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Employment law specialists",
    "ranking": "N/A",
    "awards": "Labour law focused",
    "target": "Korporace, HR oddělení, zaměstnanci",
    "primary": "Pracovní právo a zaměstnávání"
  },
  {
    "id": 44,
    "name": "Jiří Brož",
    "firm": "Brož & Sokol & Novák",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 10,
    "areas": [
      "Duševní vlastnictví",
      "IT právo",
      "E-commerce",
      "Mediální právo"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "8",
    "verified": false,
    "key_partner": "Jiří Brož",
    "description": "Boutique kancelář zaměřená na duševní vlastnictví, IT právo a digitální ekonomiku",
    "website": "www.brozadvokati.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "BS",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "IP/tech specialists",
    "ranking": "N/A",
    "awards": "Growing IP boutique",
    "target": "Technologické firmy, startupy, kreativci",
    "primary": "Duševní vlastnictví a technologie"
  },
  {
    "id": 45,
    "name": "Havel & Partners (Startup/VC division)",
    "firm": "Havel & Partners (Startup/VC division)",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 17,
    "areas": [
      "Venture Capital",
      "Poradenství pro startupy",
      "Obchodní právo",
      "Duševní vlastnictví",
      "Fúze a akvizice",
      "IT právo"
    ],
    "type": "Velká národní kancelář",
    "founded": 2001,
    "size": "350+",
    "verified": true,
    "key_partner": "",
    "description": "Specializovaný tým pro startupy a venture capital v největší české kanceláři",
    "website": "www.havelpartners.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "H(",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Dedicated startup/VC team within largest Czech firm",
    "ranking": "Tier 1 – Legal 500",
    "awards": "Startup advisory leader",
    "target": "Startupy, VC investoři, technologické firmy",
    "primary": "Startupy a venture capital"
  },
  {
    "id": 46,
    "name": "Dentons (Startup division)",
    "firm": "Dentons (Startup division)",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 24,
    "areas": [
      "Venture Finance",
      "Poradenství pro startupy",
      "Obchodní právo",
      "Fúze a akvizice",
      "Duševní vlastnictví"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2013,
    "size": "35+",
    "verified": false,
    "key_partner": "",
    "description": "Součást globální inovační platformy Nextlaw (Dentons) pro startupy a technologické firmy",
    "website": "www.dentons.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "D(",
    "hourly_rate": "4,000–7,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Global startup initiative (Nextlaw)",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Global startup network",
    "target": "Startupy, VC investoři, scale-upy",
    "primary": "Startupy a venture capital"
  },
  {
    "id": 47,
    "name": "Vladimír Kausta",
    "firm": "AK Kausta, Opluštil & Partners",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 31,
    "areas": [
      "Náhrada škody na zdraví",
      "Pojišťovací právo",
      "Zdravotnické pochybení",
      "Spory a rozhodčí řízení"
    ],
    "type": "Butique kancelář",
    "founded": 2000,
    "size": "10+",
    "verified": true,
    "key_partner": "Vladimír Kausta",
    "description": "Kancelář se zkušenostmi s náhradou škody na zdraví a pojistnými spory",
    "website": "www.kausta.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "AK",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Personal injury specialists",
    "ranking": "N/A",
    "awards": "Experienced personal injury firm",
    "target": "Fyzické osoby, pojišťovny",
    "primary": "Škody na zdraví a pojištění"
  },
  {
    "id": 48,
    "name": "Marek Bruna",
    "firm": "Advokátní kancelář Bruna",
    "city": "Praha",
    "rating": 4.6,
    "reviews": 38,
    "areas": [
      "Rodinné právo",
      "Rozvod",
      "Péče o děti",
      "Dědické právo",
      "Občanské právo",
      "Nemovitosti"
    ],
    "type": "Malá kancelář",
    "founded": 2005,
    "size": "3",
    "verified": true,
    "key_partner": "Marek Bruna",
    "description": "Malá kancelář specializující se na rodinné právo s dostupnými sazbami",
    "website": "www.akbruna.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "BR",
    "hourly_rate": "1,500–2,500",
    "consult_fee": "First consultation 1,000 CZK",
    "pricing_note": "Affordable family law practitioner",
    "ranking": "N/A",
    "awards": "Highly rated on Google",
    "target": "Fyzické osoby, rodiny",
    "primary": "Rodinné právo"
  },
  {
    "id": 49,
    "name": "Lukáš Cink",
    "firm": "Advokátní kancelář CINK",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 45,
    "areas": [
      "Trestní právo",
      "Správní právo",
      "Dopravní přestupky",
      "Občanské právo"
    ],
    "type": "Butique kancelář",
    "founded": 2012,
    "size": "5",
    "verified": true,
    "key_partner": "Lukáš Cink",
    "description": "Boutique kancelář známá trestní obhajobou a správním řízením",
    "website": "www.akcink.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "CI",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Criminal defense focused",
    "ranking": "N/A",
    "awards": "Well-reviewed criminal defense",
    "target": "Fyzické osoby, malé firmy",
    "primary": "Trestní obhajoba"
  },
  {
    "id": 50,
    "name": "Pavel Mašek",
    "firm": "Mašek & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 7,
    "areas": [
      "Daně",
      "Obchodní právo",
      "Fúze a akvizice",
      "Převodní ceny",
      "DPH"
    ],
    "type": "Butique kancelář",
    "founded": 2007,
    "size": "8",
    "verified": false,
    "key_partner": "Pavel Mašek",
    "description": "Boutique kancelář zaměřená na daňové poradenství a korporátní strukturování",
    "website": "www.masekpartners.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "MA",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Tax advisory focus",
    "ranking": "N/A",
    "awards": "Tax and transfer pricing experts",
    "target": "Korporace, nadnárodní firmy, movití klienti",
    "primary": "Daně a korporátní právo"
  },
  {
    "id": 51,
    "name": "Rödl & Partner Prague",
    "firm": "Rödl & Partner Prague",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 14,
    "areas": [
      "Daně",
      "Audit",
      "Obchodní právo",
      "Pracovní právo",
      "Nemovitosti",
      "Compliance"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1994,
    "size": "50+",
    "verified": true,
    "key_partner": "",
    "description": "Integrovaná kancelář profesionálních služeb nabízející právo, daně a audit",
    "website": "www.roedl.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "RP",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "German-origin audit/tax/law firm",
    "ranking": "N/A",
    "awards": "Integrated legal/tax/audit services",
    "target": "Německé firmy, korporace, SME",
    "primary": "Daně a audit"
  },
  {
    "id": 52,
    "name": "KPMG Legal Prague",
    "firm": "KPMG Legal Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 21,
    "areas": [
      "Daně",
      "Regulatorní právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Compliance"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2000,
    "size": "30+",
    "verified": false,
    "key_partner": "",
    "description": "Právní složka KPMG poskytující integrované daňové, právní a poradenské služby",
    "website": "www.kpmg.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "KP",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of KPMG global network",
    "ranking": "N/A",
    "awards": "Big 4 integrated legal services",
    "target": "Korporace, nadnárodní společnosti",
    "primary": "Daně a regulace"
  },
  {
    "id": 53,
    "name": "Deloitte Legal Prague",
    "firm": "Deloitte Legal Prague",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 28,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Daně",
      "Nemovitosti",
      "Pracovní právo",
      "Compliance"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2002,
    "size": "25+",
    "verified": false,
    "key_partner": "",
    "description": "Právní složka Deloitte poskytující korporátní, daňové a poradenské právní služby",
    "website": "www.deloittelegal.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština"
    ],
    "initials": "DP",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of Deloitte global network",
    "ranking": "N/A",
    "awards": "Big 4 integrated legal services",
    "target": "Korporace, nadnárodní společnosti",
    "primary": "Korporátní právo a daně"
  },
  {
    "id": 54,
    "name": "Radek Závodný",
    "firm": "Z/C/H Legal",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 35,
    "areas": [
      "Nemovitosti",
      "Stavební právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Spory a rozhodčí řízení"
    ],
    "type": "Butique kancelář",
    "founded": 2012,
    "size": "12",
    "verified": true,
    "key_partner": "Radek Závodný",
    "description": "Boutique kancelář specializující se na realitní a stavební transakce",
    "website": "www.zchlegal.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "Z/",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Real estate transaction specialists",
    "ranking": "N/A",
    "awards": "Strong real estate practice",
    "target": "Developeři, investoři, banky",
    "primary": "Nemovitosti"
  },
  {
    "id": 55,
    "name": "Rödl & Partner (Immigration division)",
    "firm": "Rödl & Partner (Immigration division)",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 42,
    "areas": [
      "Imigrace",
      "Pracovní povolení",
      "Pobytová práva",
      "Služby pro expaty"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1994,
    "size": "50+",
    "verified": true,
    "key_partner": "",
    "description": "Imigrační služby v rámci integrované právní, daňové a auditorské kanceláře",
    "website": "www.roedl.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Ruština"
    ],
    "initials": "RP",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Immigration within integrated services",
    "ranking": "N/A",
    "awards": "Integrated immigration/corporate",
    "target": "Korporace, expati, zahraniční pracovníci",
    "primary": "Imigrační právo"
  },
  {
    "id": 56,
    "name": "Lukáš Jansa",
    "firm": "Jansa, Mokrý, Otevřel & Partners",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 4,
    "areas": [
      "IT právo",
      "E-commerce",
      "Duševní vlastnictví",
      "Spory a rozhodčí řízení",
      "Smluvní právo"
    ],
    "type": "Butique kancelář",
    "founded": 2004,
    "size": "10+",
    "verified": true,
    "key_partner": "Lukáš Jansa",
    "description": "Kancelář specializující se na IT právo, e-commerce a digitální podnikání",
    "website": "www.lawyer.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "JM",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "IT and e-commerce focused",
    "ranking": "N/A",
    "awards": "Leading IT law firm",
    "target": "Technologické firmy, e-commerce, startupy",
    "primary": "IT právo a e-commerce"
  },
  {
    "id": 57,
    "name": "Petr Lukajka",
    "firm": "Advokátní kancelář LUKAJKA & PARTNERS",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 11,
    "areas": [
      "Nemovitosti",
      "Obchodní právo",
      "Stavební právo"
    ],
    "type": "Butique kancelář",
    "founded": 2011,
    "size": "5",
    "verified": true,
    "key_partner": "Petr Lukajka",
    "description": "Specializovaná kancelář pro koupi nemovitostí, nájmy a majetkové spory",
    "website": "www.lukajka.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "LU",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Affordable real estate law",
    "ranking": "N/A",
    "awards": "Highly rated real estate",
    "target": "Kupující nemovitostí, pronajímatelé, nájemníci",
    "primary": "Nemovitosti"
  },
  {
    "id": 58,
    "name": "Blanka Holubová",
    "firm": "Holubová advokáti",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 18,
    "areas": [
      "Imigrace",
      "Pracovní právo",
      "Obchodní právo",
      "Pracovní povolení"
    ],
    "type": "Butique kancelář",
    "founded": 2005,
    "size": "8",
    "verified": true,
    "key_partner": "Blanka Holubová",
    "description": "Kancelář specializující se na imigrační právo se silnou rusko- a ukrajinojazyčnou podporou",
    "website": "www.holubova.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Ruština",
      "Ukrainian"
    ],
    "initials": "HA",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation 1,500 CZK",
    "pricing_note": "Expat-friendly immigration firm",
    "ranking": "N/A",
    "awards": "Top immigration practitioner",
    "target": "Expati, zahraniční pracovníci, firmy",
    "primary": "Imigrace a pracovní právo"
  },
  {
    "id": 59,
    "name": "Jan Daniš",
    "firm": "Daniš Brada",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 25,
    "areas": [
      "Bankovní právo",
      "Fúze a akvizice",
      "Nemovitosti",
      "Insolvence"
    ],
    "type": "Butique kancelář",
    "founded": 2013,
    "size": "15+",
    "verified": false,
    "key_partner": "Jan Daniš",
    "description": "Boutique kancelář s hlubokou expertízou v bankovnictví, financích a kapitálových trzích",
    "website": "www.danisbrada.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "DB",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Banking & finance specialists",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Strong finance practice",
    "target": "Banky, fondy, korporace",
    "primary": "Bankovnictví a financování"
  },
  {
    "id": 60,
    "name": "BDO Legal Prague",
    "firm": "BDO Legal Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 32,
    "areas": [
      "Daně",
      "Obchodní právo",
      "Pracovní právo",
      "Nemovitosti",
      "Compliance",
      "Insolvence"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2005,
    "size": "15+",
    "verified": false,
    "key_partner": "",
    "description": "Právní složka BDO poskytující integrované daňové, korporátní a poradenské služby",
    "website": "www.bdo.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "BP",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of BDO global network",
    "ranking": "N/A",
    "awards": "Integrated legal/audit services",
    "target": "SME, korporace, nadnárodní firmy",
    "primary": "Daně a korporátní právo"
  },
  {
    "id": 61,
    "name": "UNICONSULT",
    "firm": "UNICONSULT",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 39,
    "areas": [
      "Imigrace",
      "Povolení k pobytu",
      "Pracovní povolení",
      "Víza"
    ],
    "type": "Butique kancelář",
    "founded": 2002,
    "size": "6",
    "verified": true,
    "key_partner": "",
    "description": "Specializované imigrační služby se silnou podporou asijských a východoevropských jazyků",
    "website": "www.uniconsult.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Ruština",
      "Vietnamese"
    ],
    "initials": "UN",
    "hourly_rate": "1,500–3,000",
    "consult_fee": "Initial consultation from 1,000 CZK",
    "pricing_note": "Budget-friendly immigration services",
    "ranking": "N/A",
    "awards": "Experienced immigration firm",
    "target": "Expati, zahraniční pracovníci, podnikatelé",
    "primary": "Imigrační právo"
  },
  {
    "id": 62,
    "name": "František Vyskočil",
    "firm": "Vyskočil, Krošlák a spol.",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 46,
    "areas": [
      "Spory a rozhodčí řízení",
      "Obchodní právo",
      "Fúze a akvizice",
      "Duševní vlastnictví",
      "Nemovitosti",
      "Trestní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 1990,
    "size": "20+",
    "verified": false,
    "key_partner": "František Vyskočil",
    "description": "Jedna z prvních českých kanceláří vzniklých po sametové revoluci",
    "website": "www.akvk.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština",
      "Ruština"
    ],
    "initials": "VK",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "By arrangement",
    "pricing_note": "One of the oldest post-1989 firms",
    "ranking": "N/A",
    "awards": "Long-established firm",
    "target": "Korporace, fyzické osoby, SME",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 63,
    "name": "Jan Kříž",
    "firm": "KŘÍŽ A BĚLINA",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 8,
    "areas": [
      "Pracovní právo",
      "Sociální zabezpečení",
      "Právní HR poradenství",
      "Kolektivní vyjednávání"
    ],
    "type": "Butique kancelář",
    "founded": 2004,
    "size": "6",
    "verified": false,
    "key_partner": "Jan Kříž",
    "description": "Akademicky propojená kancelář kombinující teorii a praxi pracovního práva",
    "website": "www.krizbel.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "KB",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Pure employment law specialists",
    "ranking": "Recommended – Legal 500",
    "awards": "Academic-connected employment experts",
    "target": "Korporace, HR oddělení, odbory",
    "primary": "Pracovní právo a zaměstnávání"
  },
  {
    "id": 64,
    "name": "NWD Legal",
    "firm": "NWD Legal",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 15,
    "areas": [
      "Insolvence",
      "Bankovní právo",
      "Spory a rozhodčí řízení",
      "Obchodní právo"
    ],
    "type": "Butique kancelář",
    "founded": 2009,
    "size": "8",
    "verified": false,
    "key_partner": "",
    "description": "Specializovaná kancelář pro korporátní insolvenci a restrukturalizační řízení",
    "website": "www.nwd.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "NW",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Insolvency specialists",
    "ranking": "N/A",
    "awards": "Strong insolvency track record",
    "target": "Banky, věřitelé, korporace v tísni",
    "primary": "Insolvence a restrukturalizace"
  },
  {
    "id": 65,
    "name": "BPV Braun Partners",
    "firm": "BPV Braun Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 22,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Nemovitosti",
      "Bankovní právo",
      "Pracovní právo",
      "Spory a rozhodčí řízení"
    ],
    "type": "Střední národní kancelář",
    "founded": 2005,
    "size": "30+",
    "verified": false,
    "key_partner": "",
    "description": "Středně velká kancelář s mezinárodní orientací a sítí v regionu CEE",
    "website": "www.bfrpartners.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Ruština"
    ],
    "initials": "BB",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "International focus with CEE network",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Growing mid-size firm",
    "target": "Korporace, nadnárodní firmy, investoři",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 66,
    "name": "Mojmír Ježek",
    "firm": "ECOVIS ježek",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 29,
    "areas": [
      "Obchodní právo",
      "Nemovitosti",
      "Imigrace",
      "Pracovní právo",
      "Spory a rozhodčí řízení",
      "Financování"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2006,
    "size": "15+",
    "verified": true,
    "key_partner": "Mojmír Ježek",
    "description": "Česká kancelář se silným poradenstvím pro expaty a mezinárodní sítí",
    "website": "www.ecovislegal.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Ruština"
    ],
    "initials": "EJ",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of ECOVIS international network",
    "ranking": "N/A",
    "awards": "Strong expat services",
    "target": "Expati, SME, korporace",
    "primary": "Komplexní služby (expati)"
  },
  {
    "id": 67,
    "name": "Tomáš Toman",
    "firm": "Chrenek, Toman, Kotrba",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 36,
    "areas": [
      "Zdravotnictví",
      "Farmaceutické právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Compliance"
    ],
    "type": "Střední národní kancelář",
    "founded": 2010,
    "size": "20+",
    "verified": false,
    "key_partner": "Tomáš Toman",
    "description": "Oceňovaná kancelář specializující se na zdravotnické a farmaceutické právo",
    "website": "www.chrenektomankotrba.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Slovenština"
    ],
    "initials": "CT",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Healthcare law specialists – Firm of the Year 2025",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Law Firm of the Year 2025 – Healthcare",
    "target": "Zdravotnictví, farma, nemocnice",
    "primary": "Zdravotnické právo"
  },
  {
    "id": 68,
    "name": "David Borkovec",
    "firm": "DBK Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 43,
    "areas": [
      "Energetika",
      "Infrastruktura",
      "Veřejně-soukromá partnerství",
      "Obchodní právo",
      "Fúze a akvizice",
      "Nemovitosti"
    ],
    "type": "Střední národní kancelář",
    "founded": 2012,
    "size": "20+",
    "verified": false,
    "key_partner": "David Borkovec",
    "description": "Oceňovaná kancelář specializující se na energetiku, infrastrukturu a projektové financování",
    "website": "www.dbkp.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "DB",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Law Firm of the Year 2025 – Energy",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Law Firm of the Year 2025 – Energy & Czech firm on international markets",
    "target": "Energetické firmy, stát, developeři",
    "primary": "Energetika a infrastruktura"
  },
  {
    "id": 69,
    "name": "PORTOS advokátní kancelář",
    "firm": "PORTOS advokátní kancelář",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 5,
    "areas": [
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Fúze a akvizice"
    ],
    "type": "Střední národní kancelář",
    "founded": 2008,
    "size": "15+",
    "verified": false,
    "key_partner": "",
    "description": "Oceňovaná kancelář známá obchodním právem a arbitráží",
    "website": "www.portos.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "PO",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Law Firm of the Year 2025 – Commercial & Arbitration",
    "ranking": "N/A",
    "awards": "Law Firm of the Year 2025 – Commercial Law, Dispute Resolution",
    "target": "Korporace, malé a střední podniky",
    "primary": "Obchodní právo a spory"
  },
  {
    "id": 70,
    "name": "Pavol Kehl",
    "firm": "Pavol Kehl – Immigration Lawyer",
    "city": "Praha",
    "rating": 4.7,
    "reviews": 12,
    "areas": [
      "Imigrace",
      "Trestní právo",
      "Pobytová práva",
      "Deportace",
      "Duševní vlastnictví",
      "Azylové řízení"
    ],
    "type": "Malá kancelář",
    "founded": 2010,
    "size": "2",
    "verified": true,
    "key_partner": "Pavol Kehl",
    "description": "Sólový advokát specializující se na imigraci a trestní právo pro cizince",
    "website": "www.kehl.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Slovenština"
    ],
    "initials": "PK",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Specialist immigration lawyer",
    "ranking": "N/A",
    "awards": "Highly rated immigration specialist",
    "target": "Expati, uprchlíci, zahraniční pracovníci",
    "primary": "Imigrační a trestní právo"
  },
  {
    "id": 71,
    "name": "Vercímák",
    "firm": "Vercímák Law",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 19,
    "areas": [
      "Imigrace",
      "Azylové řízení",
      "Rodinné právo",
      "Rozvod",
      "Občanské právo",
      "Obchodní právo"
    ],
    "type": "Malá kancelář",
    "founded": 2012,
    "size": "3",
    "verified": true,
    "key_partner": "Vercímák",
    "description": "Malá kancelář pomáhající cizincům s imigrací, azylem a rodinným právem",
    "website": "www.vercimak.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "VE",
    "hourly_rate": "1,500–2,500",
    "consult_fee": "First consultation from 1,000 CZK",
    "pricing_note": "Affordable immigration/family law",
    "ranking": "N/A",
    "awards": "Consumer-friendly",
    "target": "Expati, rodiny, uprchlíci",
    "primary": "Imigrační a rodinné právo"
  },
  {
    "id": 72,
    "name": "Expat Advisors / Rutland & Partners",
    "firm": "Expat Advisors / Rutland & Partners",
    "city": "Praha",
    "rating": 4.6,
    "reviews": 26,
    "areas": [
      "Imigrace",
      "Nemovitosti",
      "Rodinné právo",
      "Pracovní právo",
      "Závěti a svěřenské fondy",
      "Obchodní právo"
    ],
    "type": "Butique kancelář",
    "founded": 2012,
    "size": "10+",
    "verified": true,
    "key_partner": "",
    "description": "Komplexní právní a relokační služby pro expaty v České republice",
    "website": "www.expatadvisors.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Ruština"
    ],
    "initials": "EA",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "First consultation from 2,000 CZK",
    "pricing_note": "Full-service expat advisory",
    "ranking": "N/A",
    "awards": "200+ real estate transactions completed",
    "target": "Expati, zahraniční investoři, rodiny",
    "primary": "Právní služby pro expaty"
  },
  {
    "id": 73,
    "name": "Pajerová Sedláčková Advokátky",
    "firm": "Pajerová Sedláčková Advokátky",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 33,
    "areas": [
      "Obchodní právo",
      "Nemovitosti",
      "Rodinné právo",
      "Revize smluv",
      "Pobytová práva"
    ],
    "type": "Malá kancelář",
    "founded": 1995,
    "size": "4",
    "verified": true,
    "key_partner": "",
    "description": "Jedna z nejdéle působících kanceláří zaměřených na expaty v Praze",
    "website": "www.pajerovasedlackova.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Ruština"
    ],
    "initials": "PS",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Helping expats since the 1990s",
    "ranking": "N/A",
    "awards": "Veteran expat-serving firm",
    "target": "Expati, malé firmy, rodiny",
    "primary": "Právní služby pro expaty"
  },
  {
    "id": 74,
    "name": "Barbora Karetová",
    "firm": "Expat Law (Barbora Karetová)",
    "city": "Praha",
    "rating": 4.7,
    "reviews": 40,
    "areas": [
      "Rodinné právo",
      "Dědické právo",
      "Pracovní právo",
      "Nemovitosti",
      "Občanské právo"
    ],
    "type": "Malá kancelář",
    "founded": 2014,
    "size": "3",
    "verified": true,
    "key_partner": "Barbora Karetová",
    "description": "Specialistka pomáhající expatům v oblasti rodinného práva, dědictví a zaměstnání",
    "website": "www.expatlaw.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "E(",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Expat-focused family law",
    "ranking": "N/A",
    "awards": "Highly rated expat lawyer",
    "target": "Expati, rodiny, zaměstnanci",
    "primary": "Rodinné a dědické právo"
  },
  {
    "id": 75,
    "name": "Giese & Partner",
    "firm": "Giese & Partner",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 47,
    "areas": [
      "Nemovitosti",
      "Bankovní právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Stavební právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1998,
    "size": "25+",
    "verified": false,
    "key_partner": "",
    "description": "Kancelář se sídlem v Německu se silnou praxí v nemovitostech a bankovnictví",
    "website": "www.giese.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "GP",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "German-origin firm, strong in real estate and finance",
    "ranking": "Tier 2 – Legal 500 (Real Estate)",
    "awards": "Ranked Legal 500 EMEA 2025",
    "target": "Banky, developeři, investoři",
    "primary": "Nemovitosti a financování"
  },
  {
    "id": 76,
    "name": "AZ LEGAL",
    "firm": "AZ LEGAL",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 9,
    "areas": [
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Nemovitosti",
      "Pracovní právo",
      "Rodinné právo",
      "Imigrace"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "8",
    "verified": true,
    "key_partner": "",
    "description": "Boutique kancelář nabízející dostupné komplexní právní služby",
    "website": "www.azlegal.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "AZ",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation available",
    "pricing_note": "Consumer-friendly boutique",
    "ranking": "N/A",
    "awards": "Well-reviewed Prague boutique",
    "target": "Fyzické osoby, SME, expati",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 77,
    "name": "Jan Vejmelka",
    "firm": "Vejmelka & Wünsch",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 16,
    "areas": [
      "Bankovní právo",
      "Fúze a akvizice",
      "Private Equity",
      "Obchodní právo",
      "Nemovitosti",
      "Insolvence"
    ],
    "type": "Butique kancelář",
    "founded": 2015,
    "size": "10+",
    "verified": false,
    "key_partner": "Jan Vejmelka",
    "description": "Boutique kancelář se silnou bankovní, M&A a fintechovou poradenskou praxí",
    "website": "www.vejmelka.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "VW",
    "hourly_rate": "3,000–5,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong in banking and M&A fintech",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Praised for fintech expertise",
    "target": "Banky, fintech společnosti, PE fondy",
    "primary": "Bankovnictví a fúze"
  },
  {
    "id": 78,
    "name": "Linklaters Prague",
    "firm": "Linklaters Prague",
    "city": "Praha",
    "rating": 4.3,
    "reviews": 23,
    "areas": [
      "Bankovní právo",
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Soutěžní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1996,
    "size": "20+",
    "verified": true,
    "key_partner": "",
    "description": "Kancelář ze skupiny Magic Circle s vedoucí bankovní a kapitálotržní praxí",
    "website": "www.linklaters.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "LP",
    "hourly_rate": "5,000–8,000+",
    "consult_fee": "By arrangement",
    "pricing_note": "Magic Circle premium rates",
    "ranking": "Tier 1 – Legal 500 (Banking)",
    "awards": "Magic Circle firm",
    "target": "Banky, nadnárodní společnosti, PE fondy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 79,
    "name": "Freshfields Bruckhaus Deringer Prague",
    "firm": "Freshfields Bruckhaus Deringer Prague",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 30,
    "areas": [
      "Fúze a akvizice",
      "Bankovní právo",
      "Spory a rozhodčí řízení",
      "Soutěžní právo",
      "Nemovitosti"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 1991,
    "size": "15+",
    "verified": true,
    "key_partner": "",
    "description": "Kancelář ze skupiny Magic Circle s dlouholetou přítomností v Praze",
    "website": "www.freshfields.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "FB",
    "hourly_rate": "5,000–8,000+",
    "consult_fee": "By arrangement",
    "pricing_note": "Magic Circle premium rates",
    "ranking": "Tier 1 – Legal 500",
    "awards": "Leading international firm",
    "target": "Nadnárodní firmy, banky, PE fondy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 80,
    "name": "EY Law Prague",
    "firm": "EY Law Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 37,
    "areas": [
      "Daně",
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Compliance",
      "IT právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2005,
    "size": "20+",
    "verified": false,
    "key_partner": "",
    "description": "Právní složka EY poskytující integrované daňové a korporátní poradenství",
    "website": "www.ey.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "EP",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of EY global network",
    "ranking": "N/A",
    "awards": "Big 4 integrated legal services",
    "target": "Korporace, nadnárodní společnosti",
    "primary": "Daně a korporátní právo"
  },
  {
    "id": 81,
    "name": "PwC Legal Prague",
    "firm": "PwC Legal Prague",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 44,
    "areas": [
      "Daně",
      "Obchodní právo",
      "Regulatorní právo",
      "Pracovní právo",
      "Nemovitosti",
      "IT právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2004,
    "size": "15+",
    "verified": false,
    "key_partner": "",
    "description": "Právní složka PwC poskytující daňové, korporátní a regulatorní poradenství",
    "website": "www.pwc.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština"
    ],
    "initials": "PP",
    "hourly_rate": "3,500–6,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Part of PwC global network",
    "ranking": "N/A",
    "awards": "Big 4 integrated legal services",
    "target": "Korporace, nadnárodní společnosti",
    "primary": "Daně a regulace"
  },
  {
    "id": 82,
    "name": "Hogan Lovells Prague",
    "firm": "Hogan Lovells Prague",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 6,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Duševní vlastnictví",
      "IT právo",
      "Life Sciences",
      "Spory a rozhodčí řízení"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2010,
    "size": "15+",
    "verified": false,
    "key_partner": "",
    "description": "Globální kancelář s pozoruhodnou praxí v IP, technologiích a life sciences",
    "website": "www.hoganlovells.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "HL",
    "hourly_rate": "4,000–7,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Global firm with strong IP/tech",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Global top 10 firm",
    "target": "Farma, technologie, nadnárodní firmy",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 83,
    "name": "Bird & Bird Prague",
    "firm": "Bird & Bird Prague",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 13,
    "areas": [
      "Duševní vlastnictví",
      "IT právo",
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Spory a rozhodčí řízení"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2009,
    "size": "15+",
    "verified": true,
    "key_partner": "",
    "description": "Mezinárodní kancelář s hlubokou expertízou v technologiích, IP a digitálním právu",
    "website": "www.twobirds.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "BB",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Known globally for tech and IP law",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Leading tech & IP firm",
    "target": "Technologické firmy, farma, startupy",
    "primary": "Duševní vlastnictví a technologie"
  },
  {
    "id": 84,
    "name": "Osborne Clarke Prague",
    "firm": "Osborne Clarke Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 20,
    "areas": [
      "IT právo",
      "Digitální podnikání",
      "Obchodní právo",
      "Nemovitosti",
      "Pracovní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2015,
    "size": "12+",
    "verified": false,
    "key_partner": "",
    "description": "Mezinárodní kancelář zaměřená na digitální ekonomiku a technologická odvětví",
    "website": "www.osborneclarke.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "OC",
    "hourly_rate": "3,500–5,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Digital economy specialist",
    "ranking": "N/A",
    "awards": "Growing tech-focused firm",
    "target": "Technologické firmy, digitální platformy, startupy",
    "primary": "Technologie a digitální právo"
  },
  {
    "id": 85,
    "name": "Drobiš & Novotný",
    "firm": "Drobiš & Novotný",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 27,
    "areas": [
      "Náhrada škody na zdraví",
      "Dopravní nehody",
      "Pracovní úrazy",
      "Zdravotnické pochybení",
      "Pojistné nároky"
    ],
    "type": "Butique kancelář",
    "founded": 2008,
    "size": "5",
    "verified": true,
    "key_partner": "",
    "description": "Specializovaná kancelář pro oběti nehod, pracovní úrazy a zdravotnická pochybení",
    "website": "www.drobisnovotny.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "DN",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation from 1,000 CZK",
    "pricing_note": "Contingency options available",
    "ranking": "N/A",
    "awards": "Personal injury specialists",
    "target": "Fyzické osoby, oběti nehod",
    "primary": "Náhrada škody na zdraví"
  },
  {
    "id": 86,
    "name": "Silvia Borovská",
    "firm": "Silvia Borovská – Mediator & Lawyer",
    "city": "Praha",
    "rating": 4.8,
    "reviews": 34,
    "areas": [
      "Rodinné právo",
      "Mezinárodní rozvod",
      "Péče o děti",
      "Mediace"
    ],
    "type": "Malá kancelář",
    "founded": 2012,
    "size": "2",
    "verified": true,
    "key_partner": "Silvia Borovská",
    "description": "Specialista na mezinárodní rodinné právo a mediaci v přeshraničních případech",
    "website": "www.borovska.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Slovenština"
    ],
    "initials": "SB",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Mediator and lawyer",
    "ranking": "N/A",
    "awards": "Top-rated family law mediator",
    "target": "Expati, mezinárodní rodiny",
    "primary": "Mezinárodní rodinné právo"
  },
  {
    "id": 87,
    "name": "Markéta Allnutt",
    "firm": "Markéta Allnutt – Attorney",
    "city": "Praha",
    "rating": 4.7,
    "reviews": 41,
    "areas": [
      "Rozvod",
      "Péče o děti",
      "Rodinné právo",
      "Mezinárodní rozluky"
    ],
    "type": "Malá kancelář",
    "founded": 2015,
    "size": "1",
    "verified": true,
    "key_partner": "Markéta Allnutt",
    "description": "Sólová advokátka specializující se na mezinárodní rozvod a péči o děti pro expaty",
    "website": "www.allnuttlaw.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "MA",
    "hourly_rate": "2,000–3,000",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Specialist in international divorce",
    "ranking": "N/A",
    "awards": "Highly rated for expat divorces",
    "target": "Expati, rodiny",
    "primary": "Rozvod a péče o děti"
  },
  {
    "id": 88,
    "name": "Stránský & Partners",
    "firm": "Stránský & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 48,
    "areas": [
      "Pracovní právo",
      "HR poradenství",
      "Sociální zabezpečení",
      "Insolvence"
    ],
    "type": "Butique kancelář",
    "founded": 2007,
    "size": "10+",
    "verified": false,
    "key_partner": "",
    "description": "Boutique kancelář zaměřená na pracovní právo a HR právní poradenství",
    "website": "www.stranskypartners.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "ST",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Employment law boutique",
    "ranking": "N/A",
    "awards": "Established employment practice",
    "target": "Korporace, HR oddělení",
    "primary": "Pracovní právo a zaměstnávání"
  },
  {
    "id": 89,
    "name": "Halška & Partners",
    "firm": "Halška & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 10,
    "areas": [
      "Mediace",
      "Spory a rozhodčí řízení",
      "Alternativní řešení sporů",
      "Obchodní právo",
      "Rodinné právo",
      "Občanské právo"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "5",
    "verified": false,
    "key_partner": "",
    "description": "Kancelář specializující se na mediaci a alternativní řešení sporů",
    "website": "www.halska.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "HA",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "Mediation from 2,000 CZK/hour",
    "pricing_note": "Alternative dispute resolution focus",
    "ranking": "N/A",
    "awards": "ADR specialists",
    "target": "Korporace, fyzické osoby, rodiny",
    "primary": "Mediace a alternativní spory"
  },
  {
    "id": 90,
    "name": "Kopřiva & Švehlík",
    "firm": "Kopřiva & Švehlík",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 17,
    "areas": [
      "Stavební právo",
      "Nemovitosti",
      "Správní právo",
      "Infrastruktura",
      "Veřejně-soukromá partnerství"
    ],
    "type": "Butique kancelář",
    "founded": 2011,
    "size": "8",
    "verified": false,
    "key_partner": "",
    "description": "Boutique kancelář s hlubokou expertízou ve stavebnictví, infrastruktuře a PPP projektech",
    "website": "www.koprivasve.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "KŠ",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Construction law specialists",
    "ranking": "N/A",
    "awards": "Niche construction practice",
    "target": "Developeři, dodavatelé, státní správa",
    "primary": "Stavební právo a nemovitosti"
  },
  {
    "id": 91,
    "name": "Norton Rose Fulbright Prague",
    "firm": "Norton Rose Fulbright Prague",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 24,
    "areas": [
      "Bankovní právo",
      "Obchodní právo",
      "Spory a rozhodčí řízení",
      "Energetika",
      "Nemovitosti",
      "Regulatorní právo"
    ],
    "type": "Mezinárodní kancelář",
    "founded": 2005,
    "size": "15+",
    "verified": false,
    "key_partner": "",
    "description": "Přední globální kancelář se silnými stránkami v energetice, bankovnictví a sporech",
    "website": "www.nortonrosefulbright.com",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "NR",
    "hourly_rate": "4,000–6,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Global firm with energy focus",
    "ranking": "Tier 2 – Legal 500",
    "awards": "Top global firm",
    "target": "Energetické firmy, banky, korporace",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 92,
    "name": "Dvořák & Partners",
    "firm": "Dvořák & Partners",
    "city": "Praha",
    "rating": 4.2,
    "reviews": 31,
    "areas": [
      "Obchodní právo",
      "Nemovitosti",
      "Fúze a akvizice",
      "Stavební právo",
      "Spory a rozhodčí řízení",
      "Pracovní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 2001,
    "size": "15+",
    "verified": true,
    "key_partner": "",
    "description": "Zavedená středně velká kancelář se silnou korporátní a realitní praxí",
    "website": "www.dvorakpartners.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "DV",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong corporate and real estate",
    "ranking": "N/A",
    "awards": "Established mid-size firm",
    "target": "Developeři, korporace, SME",
    "primary": "Korporátní právo a nemovitosti"
  },
  {
    "id": 93,
    "name": "Císař, Češka, Smutný",
    "firm": "Císař, Češka, Smutný",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 38,
    "areas": [
      "Správní právo",
      "Obchodní právo",
      "Nemovitosti",
      "Spory a rozhodčí řízení",
      "Soutěžní právo"
    ],
    "type": "Střední národní kancelář",
    "founded": 2002,
    "size": "25+",
    "verified": false,
    "key_partner": "",
    "description": "Kancelář se silnou expertízou ve veřejných zakázkách a správním řízení",
    "website": "www.akccs.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "CČ",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Strong in public procurement and administrative law",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Public sector specialist",
    "target": "Státní správa, veřejný sektor, korporace",
    "primary": "Veřejné zakázky a správní právo"
  },
  {
    "id": 94,
    "name": "Toman & Partners",
    "firm": "Toman & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 45,
    "areas": [
      "Životní prostředí",
      "Energetika",
      "Regulatorní právo",
      "Správní právo",
      "Nemovitosti",
      "Stavební právo"
    ],
    "type": "Butique kancelář",
    "founded": 2008,
    "size": "10+",
    "verified": false,
    "key_partner": "",
    "description": "Boutique kancelář specializující se na environmentální právo, energetickou regulaci a permitting",
    "website": "www.tomanpartners.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "TO",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Environmental law specialists",
    "ranking": "N/A",
    "awards": "Growing environmental practice",
    "target": "Energetické firmy, developeři, stát",
    "primary": "Environmentální právo"
  },
  {
    "id": 95,
    "name": "Multiple Lawyers",
    "firm": "Czech Lawyers (online platform)",
    "city": "Praha",
    "rating": 4.5,
    "reviews": 7,
    "areas": [
      "Imigrace",
      "Obchodní právo",
      "Nemovitosti",
      "Rodinné právo",
      "Smluvní právo",
      "Spory a rozhodčí řízení"
    ],
    "type": "Butique kancelář",
    "founded": 2010,
    "size": "6",
    "verified": true,
    "key_partner": "Multiple Lawyers",
    "description": "Online platforma právních služeb pro cizince v České republice",
    "website": "www.czech-lawyers.com",
    "languages": [
      "Čeština",
      "Angličtina",
      "Ruština",
      "Němčina",
      "Francouzština"
    ],
    "initials": "CL",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,000 CZK",
    "pricing_note": "Online-first expat legal services",
    "ranking": "N/A",
    "awards": "Top online expat legal platform",
    "target": "Expati, zahraniční investoři, startupy",
    "primary": "Právní služby pro expaty"
  },
  {
    "id": 96,
    "name": "Pokorný, Wagner & Partners",
    "firm": "Pokorný, Wagner & Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 14,
    "areas": [
      "Duševní vlastnictví",
      "Mediální právo",
      "Autorské právo",
      "Ochranné známky",
      "Zábavní průmysl",
      "Reklamní právo"
    ],
    "type": "Butique kancelář",
    "founded": 2006,
    "size": "8",
    "verified": false,
    "key_partner": "",
    "description": "Boutique kancelář specializující se na IP, média, zábavní průmysl a reklamu",
    "website": "www.pokornywagner.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "PW",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "IP and media specialists",
    "ranking": "N/A",
    "awards": "Strong media/entertainment practice",
    "target": "Mediální firmy, kreativci, vydavatelé",
    "primary": "Duševní vlastnictví a média"
  },
  {
    "id": 97,
    "name": "Holec Zuska Partners",
    "firm": "Holec Zuska Partners",
    "city": "Praha",
    "rating": 4.0,
    "reviews": 21,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Pracovní právo",
      "Nemovitosti",
      "Bankovní právo",
      "Spory a rozhodčí řízení"
    ],
    "type": "Střední národní kancelář",
    "founded": 2000,
    "size": "20+",
    "verified": false,
    "key_partner": "",
    "description": "Zavedená středně velká kancelář pokrývající korporátní a obchodní právo",
    "website": "www.holeczuska.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "HZ",
    "hourly_rate": "2,500–4,000",
    "consult_fee": "By arrangement",
    "pricing_note": "Established mid-size full-service",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Reliable mid-size firm",
    "target": "Korporace, SME, banky",
    "primary": "Komplexní právní služby"
  },
  {
    "id": 98,
    "name": "Jan Hartmann",
    "firm": "Advokátní kancelář Hartmann",
    "city": "Praha",
    "rating": 4.4,
    "reviews": 28,
    "areas": [
      "Trestní právo",
      "Hospodářská kriminalita",
      "Podvody",
      "Správní právo"
    ],
    "type": "Malá kancelář",
    "founded": 2005,
    "size": "3",
    "verified": true,
    "key_partner": "Jan Hartmann",
    "description": "Zkušený trestní obhájce řešící složité případy podvodů a hospodářské kriminality",
    "website": "www.akhartmann.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina"
    ],
    "initials": "HA",
    "hourly_rate": "2,000–3,500",
    "consult_fee": "First consultation from 1,500 CZK",
    "pricing_note": "Experienced criminal lawyer",
    "ranking": "N/A",
    "awards": "Well-regarded criminal defense",
    "target": "Fyzické osoby, manažeři",
    "primary": "Trestní obhajoba"
  },
  {
    "id": 99,
    "name": "Jakub Dáňa",
    "firm": "Advokátní kancelář Dáňa",
    "city": "Praha",
    "rating": 4.6,
    "reviews": 35,
    "areas": [
      "Rodinné právo",
      "Rozvod",
      "Dědické právo",
      "Občanské právo",
      "Vymáhání pohledávek",
      "Nemovitosti"
    ],
    "type": "Malá kancelář",
    "founded": 2013,
    "size": "2",
    "verified": true,
    "key_partner": "Jakub Dáňa",
    "description": "Dostupná sólová advokátka specializující se na rodinné právo a občanskoprávní věci",
    "website": "www.akdana.cz",
    "languages": [
      "Čeština",
      "Angličtina"
    ],
    "initials": "DÁ",
    "hourly_rate": "1,500–2,500",
    "consult_fee": "First consultation from 1,000 CZK",
    "pricing_note": "Budget-friendly family law",
    "ranking": "N/A",
    "awards": "Highly rated by individuals",
    "target": "Fyzické osoby, rodiny",
    "primary": "Rodinné a občanské právo"
  },
  {
    "id": 100,
    "name": "JSK advokátní kancelář",
    "firm": "JSK advokátní kancelář",
    "city": "Praha",
    "rating": 4.1,
    "reviews": 42,
    "areas": [
      "Obchodní právo",
      "Fúze a akvizice",
      "Spory a rozhodčí řízení",
      "Nemovitosti",
      "Pracovní právo",
      "Duševní vlastnictví"
    ],
    "type": "Střední národní kancelář",
    "founded": 2004,
    "size": "25+",
    "verified": false,
    "key_partner": "",
    "description": "Komplexní středně velká kancelář pokrývající plný rozsah obchodního práva",
    "website": "www.jsk.cz",
    "languages": [
      "Čeština",
      "Angličtina",
      "Němčina",
      "Francouzština"
    ],
    "initials": "JS",
    "hourly_rate": "2,500–4,500",
    "consult_fee": "By arrangement",
    "pricing_note": "Comprehensive mid-size firm",
    "ranking": "Tier 3 – Legal 500",
    "awards": "Established mid-size firm",
    "target": "Korporace, SME, nadnárodní firmy",
    "primary": "Komplexní právní služby"
  }
];

const practiceAreas = [
  "Obchodní právo","Fúze a akvizice","Nemovitosti","Pracovní právo","Trestní právo",
  "Daně","Rodinné právo","IT právo","Imigrace","Insolvence","Bankovní právo",
  "Spory a rozhodčí řízení","Soutěžní právo","Duševní vlastnictví","Správní právo",
  "Stavební právo","Energetika","Životní prostředí"
];

const lawyerTypes = [
  "Butique kancelář","Střední národní kancelář","Velká národní kancelář",
  "Mezinárodní kancelář","Malá kancelář","Solo"
];

const languages = [
  "Čeština","Angličtina","Němčina","Francouzština","Slovenština",
  "Ruština","Polština","Italština","Španělština","Maďarština"
];
